version: "3"

services:
  auth-server:
    container_name: NODEJS_SERVER_AUTH
    build: "."
    volumes:
      - ./src:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3333:3333"

networks:
  default:
    external:
      name: customnet
